package eu.wltr.a2cg;


import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import javax.xml.bind.JAXBException;

import eu.wltr.a2cg.schema.ConfigUnmarshaller;
import eu.wltr.a2cg.schema.Configuration;
import eu.wltr.a2cg.schema.VirtualHost;


public class ApacheConfigGenerator {

	private final ConfigPrinter printer;
	private final Configuration config;
	private final SectionFactory sf;

	public ApacheConfigGenerator(InputStream in, OutputStream out)
			throws JAXBException {
		config = ConfigUnmarshaller.load(in);
		printer = new ConfigPrinter(out);
		sf = new SectionFactory(printer);

	}

	protected ApacheConfigGenerator(ConfigPrinter printer,
			Configuration config, SectionFactory sf) {
		this.printer = printer;
		this.config = config;
		this.sf = sf;

	}

	@SuppressWarnings({ "rawtypes", "unchecked" })
	public void generate() {

		printer.writeComment("This is an autogenerated file from a2cg.");
		printer.writeComment("Every modification will be overridden.");
		printer.writeNewline();

		for (VirtualHost host : config.getHost()) {
			printer.writeComment("");
			printer.writeComment(host.getName());
			printer.writeComment("");
			printer.beginScope("VirtualHost", "*:80");

			Map<String, Object> elements = Utils.getBeanProperties(host);

			for (ConfigRootSection section : sf.getRootSections()) {
				Object value = elements.get(section.getSlug());

				if (value == null)
					continue;

				if (value instanceof List)
					for (Object item : (List) value)
						section.print(item, host);

				else
					section.print(value, host);

			}

			printer.endScope("VirtualHost");
			printer.writeNewline();

		}

	}

}
